export let questions = [
  {
    id: 1,
    title: "How many time zones are there in Russia?",
    option1: "7",
    option2: "10",
    option3: "11",
    option4: "13",
    correctAnswer: "11",
  },
  {
    id: 2,
    title: "What's the national flower of Japan?",
    option1: "Peonies",
    option2: "Cherry blossom",
    option3: "Orchid",
    option4: "Plum blossom",
    correctAnswer: "Cherry blossom",
  },
  {
    id: 3,
    title: "How many stripes are there on the US flag?",
    option1: "8",
    option2: "10",
    option3: "13",
    option4: "15",
    correctAnswer: "13",
  },
  {
    id: 4,
    title: "What's the national animal of Australia?",
    option1: "Tasmanian devil",
    option2: "Red Kangaroo",
    option3: "Platypus",
    option4: "Emu",
    correctAnswer: "Red kangaroo",
  },
  {
    id: 5,
    title: "How many days does it take for earth to orbit the sun?",
    option1: "365",
    option2: "28",
    option3: "7",
    option4: "1",
    correctAnswer: "365",
  },
  {
    id: 6,
    title: "What's the capital of Canada?",
    option1: "Vancouver",
    option2: "Calgary",
    option3: "Montreal",
    option4: "Ottawa",
    correctAnswer: "Ottawa",
  },
  {
    id: 7,
    title: "What's the longest river in the world?",
    option1: "Mississippi",
    option2: "Yangtze",
    option3: "Nile",
    option4: "Amazon",
    correctAnswer: "Nile",
  },
  {
    id: 8,
    title: "Which famous graffiti artist comes from Bristol(UK)?",
    option1: "Jean Michel Basquiat",
    option2: "Lady Pink",
    option3: "Futura 2000",
    option4: "Banksy",
    correctAnswer: "Banksy",
  },
  {
    id: 9,
    title: "When did the London underground open?",
    option1: "1804",
    option2: "1863",
    option3: "1906",
    option4: "1875",
    correctAnswer: "1863",
  },
  {
    id: 10,
    title: "How many keys does a classic piano have?",
    option1: "80",
    option2: "92",
    option3: "88",
    option4: "66",
    correctAnswer: "88",
  },
];
